[package]
<<<<<<< HEAD
name = "seashell"
=======
name = "seamonkey"
>>>>>>> 59b0e5ffefed234bb849bc6209eb4655a6c86008
version = "0.1.0"
authors = ["ve5li <ve5li@tuta.io>"]

[dependencies]
seamonkey = { path = "/usr/share/kami/seamonkey" }
#seamonkey = { git = "https://github.com/vE5li/seamonkey.git" }
